version: "3.8"

services: 
  
    server:
      
      image: "nginx"

      ports: 
        - "8000:80"

      depends_on: 
    
        - php 


      volumes: 
    
        - ./:/var/www/html
        
      

    php:
      
      build: 
        
        context: ./dockerfiles
        
        dockerfile: php.dockerfile
      
      volumes: 
    
        - ./:/var/www/html:delegated

        - ./xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini 
      
      
    composer:

      build: 
        
        context: ./dockerfiles
        
        dockerfile: composer.dockerfile

      volumes: 
      
        - ./:/var/www/html:delegated
    
        
      
    
    

